{"name": "Тест успешного принятия заказа", "status": "failed", "statusDetails": {"message": "AssertionError: assert 409 == 200\n +  where 409 = <Response [409]>.status_code", "trace": "self = <test_accept_order.TestAcceptOrder object at 0x102539d00>, register_new_courier = <function register_new_courier.<locals>._register_new_courier at 0x1032420c0>\ngenerate_random_string = <function generate_random_string.<locals>._generate_random_string at 0x103242020>\nlogin_courier = <function login_courier.<locals>._login_courier at 0x1032425c0>, creation_order = <function creation_order.<locals>._create_order at 0x103242660>\naccept_order = <function accept_order.<locals>._accept_order at 0x10252da80>\n\n    @allure.title('Тест успешного принятия заказа')\n    def test_accept_order_success(self, register_new_courier, generate_random_string, login_courier, creation_order, accept_order):\n        login = generate_random_string()\n        password = \"password123\"\n        first_name = \"CourierTest\"\n    \n        register_response = register_new_courier(login=login, password=password, first_name=first_name)\n        assert register_response.status_code == 201\n    \n        login_response = login_courier(login=login, password=password)\n        assert login_response.status_code == 200\n    \n        courier_id = login_response.json().get(\"id\")\n        assert courier_id is not None\n    \n        order_response = creation_order(\n            first_name=\"Test\",\n            last_name=\"User\",\n            address=\"Test address\",\n            metro_station=4,\n            phone=\"+7 999 999 99 99\",\n            rent_time=5,\n            delivery_date=\"2024-10-10\",\n            comment=\"Test order\",\n            color=[]\n        )\n        assert order_response.status_code == 201\n    \n        order_id = order_response.json().get(\"track\")\n        assert order_id is not None\n    \n        accept_response = accept_order(order_id=order_id, courier_id=courier_id)\n>       assert accept_response.status_code == 200\nE       assert 409 == 200\nE        +  where 409 = <Response [409]>.status_code\n\ntests/test_accept_order.py:41: AssertionError"}, "start": 1728130994548, "stop": 1728130996435, "uuid": "2e3acf82-8959-455e-adc4-ab622f8ddc27", "historyId": "bf3d90b089133297733d4bf073c72610", "testCaseId": "bf3d90b089133297733d4bf073c72610", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_success", "labels": [{"name": "feature", "value": "Принятие заказа"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "MacBook-Air-Jobanyj.local"}, {"name": "thread", "value": "5422-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}